# Generated by Django 6.0.5 on 2026-05-19 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_inscricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='descricao',
            field=models.TextField(default='Descrição detalhada do curso...'),
        ),
        migrations.AddField(
            model_name='curso',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='curso',
            name='resumo',
            field=models.CharField(default='Resumo do curso...', max_length=250),
        ),
    ]
