# Generated by Django 6.0.5 on 2026-05-19 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_curso_descricao_curso_preco_curso_resumo'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='nota',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
