# Generated by Django 6.0.5 on 2026-05-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_inscricao_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='dias_seguidos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='ultima_interacao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
