# Generated by Django 6.0.5 on 2026-05-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_inscricao_dias_seguidos_inscricao_ultima_interacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='pensamento',
            field=models.TextField(blank=True, null=True),
        ),
    ]
