# Generated by Django 6.0.5 on 2026-06-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_inscricao_pensamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Dashboard Financeiro',
                'verbose_name_plural': 'Dashboards Financeiros',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='status',
            field=models.CharField(choices=[('andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('abandonado', 'Abandonado'), ('reembolsado', 'Reembolsado')], default='andamento', max_length=20),
        ),
    ]
