# Generated by Django 6.0.5 on 2026-06-03 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0007_dashboardfinanceiro_alter_inscricao_status'),
        ('cursos', '0007_relatorioia'),
    ]

    operations = [
    ]
