# Generated by Django 6.0.5 on 2026-06-19 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_merge_20260603_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='imagem',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=''),
        ),
    ]
